gnss_to_local_node:
  ros__parameters:
    debug_mode: true
    map_ori_path: /home/zzjun/ros2Project/gokart_ws/src/gokart-sensor/configs/pennovation/map_ori.csv
    projection_center_latitude: 39.9416
    projection_center_longitude: -75.1993
    projection_lat_span: 0.001
    projection_lon_span: 0.0016
    set_origin: false
purepursuit_node:
  ros__parameters:
    D: 1.0
    Lscale: 4.0
    Lscale_corner: 4.0
    Pscale: 4.0
    Pscale_corner: 4.0
    debug_mode: true
    interpScale: 20
    maxL: 1.0
    maxL_corner: 0.5
    maxP: 1.0
    maxP_corner: 0.3
    max_steer: 0.7
    minL: 1.0
    minL_corner: 0.5
    minP: 1.0
    minP_corner: 0.3
    vel_scale: 0.8
    wp_delim: ','
    wp_path: /home/zzjun/ros2Project/gokart_ws/src/gokart-sensor/configs/pennovation/wp.csv
    wp_skiprows: 1
