gap_follow_node:
  ros__parameters:
    danger_thres: 1.0
    drive_topic: /automous_command_to_nucleo
    max_boundary: 330
    max_gap: 90
    max_speed: 3.0
    min_boundary: 30
    min_gap: 10
    min_speed: 2.0
    safe_radius: 4
    safe_thres: 2.0
    scan_topic: /ouster/scan
    steer_speed_scale: 0.87
