gnss_to_local_node:
  ros__parameters:
    projection_center_latitude: /template/lat
    projection_center_longitude: /template/lon
    projection_lat_span: 0.0010
    projection_lon_span: 0.0016
    debug_mode: True
    set_origin: True
    map_ori_path: /template/path


wp_record_node:
  ros__parameters:
    wp_filename: "wp.csv"
    pose_topic: /gnss_ekf
    velocity: 1.0
    frequency: 2


ekf_gnss_node:
  ros__parameters:
    frequency: 50
