python_node:
  ros__parameters:
    minL: 0.6
    maxL: 0.6
    Lscale: 4.0 
    minL_corner: 0.5
    maxL_corner: 0.5
    Lscale_corner: 4.0
    interpScale: 20
    minP: 1.0
    maxP: 1.0
    Pscale: 4.0
    minP_corner: 0.3
    maxP_corner: 0.3
    Pscale_corner: 4.0
    max_steer: 0.7
    D: 1.0
    vel_scale: 1.0
    wp_delim: ','
    wp_skiprows: 1

visualize_node:
  ros__parameters:
    minL: 1.2
    maxL: 1.2
    Lscale: 4.0 
    minL_corner: 0.5
    maxL_corner: 0.5
    Lscale_corner: 4.0
    interpScale: 20
    minP: 0.6
    maxP: 0.6
    Pscale: 4.0
    minP_corner: 0.3
    maxP_corner: 0.3
    Pscale_corner: 4.0
    max_steer: 0.7
    D: 1.0
    vel_scale: 1.0
    wp_delim: ','
    wp_skiprows: 1
    
    