gnss_to_local_node:
  ros__parameters:
    projection_center_latitude: 39.9416
    projection_center_longitude: -75.1993
    projection_lat_span: 0.0010
    projection_lon_span: 0.0016
    debug_mode: True
    set_origin: False
    map_ori_path: /template/path

purepursuit_node:
  ros__parameters:
    config_path: /template/path
    corner_wp_name: "corner_wp_idx.npy"
    overtake_wp_name: "overtake_wp_idx.npy"
    wp_path: /template/path
    minL: 4.0
    maxL: 5.0
    Lscale: 4.0 
    minL_corner: 4.0
    maxL_corner: 4.0
    Lscale_corner: 4.0
    interpScale: 20
    minP: 0.6
    maxP: 0.6
    Pscale: 4.0
    minP_corner: 0.8
    maxP_corner: 0.8
    Pscale_corner: 4.0
    max_steer: 0.87
    D: 1.0
    vel_scale: 0.8
    wp_delim: ','
    wp_skiprows: 1

visualize_node:
  ros__parameters:
    config_path: /template/path
    corner_wp_name: "corner_wp_idx.npy"
    overtake_wp_name: "overtake_wp_idx.npy"
    wp_path: /template/path
    wp_delim: ','
    wp_skiprows: 1
