gnss_to_local_node:
  ros__parameters:
    debug_mode: true
    map_ori_path: /home/autoware/gokart_ws/src/gokart-sensor/configs/purdue/map_ori.csv
    projection_center_latitude: 40.4377
    projection_center_longitude: -86.9447
    projection_lat_span: 0.001
    projection_lon_span: 0.0016
    set_origin: false
purepursuit_node:
  ros__parameters:
    D: 1.0
    config_path: /home/autoware/gokart_ws/src/gokart-sensor/configs/purdue
    debug_mode: true
    interpScale: 20
    maxL: 4.0
    maxL_corner: 4.0
    maxP: 4.0
    maxP_corner: 4.0
    max_steer: 0.95
    minL: 4.0
    minL_corner: 4.0
    minP: 4.0
    minP_corner: 4.0
    vel_scale: 0.8
    wp_corner_filename: corner_wp_idx.npy
    wp_delim: ;
    wp_filename: optim_traj.csv
    wp_overtake_filename: overtake_wp_idx.npy
    wp_skiprows: 4
    wp_v_idx: 5
    wp_x_idx: 1
    wp_y_idx: 2
visualize_node:
  ros__parameters:
    config_path: /home/autoware/gokart_ws/src/gokart-sensor/configs/purdue
    wp_centerline_filename: wp.csv
    wp_corner_filename: corner_wp_idx.npy
    wp_delim: ;
    wp_filename: optim_traj.csv
    wp_overtake_filename: overtake_wp_idx.npy
    wp_skiprows: 4
    wp_track_width: 3.6
    wp_v_idx: 5
    wp_x_idx: 1
    wp_y_idx: 2
