gnss_to_local_node:
  ros__parameters:
    debug_mode: true
    map_ori_path: /home/zzjun/ros2Project/gokart_ws/src/gokart-sensor/configs/purdue/map_ori.csv
    projection_center_latitude: 39.9416
    projection_center_longitude: -75.1993
    projection_lat_span: 0.001
    projection_lon_span: 0.0016
    set_origin: false
purepursuit_node:
  ros__parameters:
    D: 1.0
    Lscale: 4.0
    Lscale_corner: 4.0
    Pscale: 4.0
    Pscale_corner: 4.0
    config_path: /home/zzjun/ros2Project/gokart_ws/src/gokart-sensor/configs/purdue
    corner_wp_name: corner_wp_idx.npy
    debug_mode: true
    interpScale: 20
    maxL: 5.0
    maxL_corner: 4.0
    maxP: 0.6
    maxP_corner: 0.8
    max_steer: 0.87
    minL: 4.0
    minL_corner: 4.0
    minP: 0.6
    minP_corner: 0.8
    overtake_wp_name: overtake_wp_idx.npy
    vel_scale: 0.8
    wp_delim: ','
    wp_path: /home/zzjun/ros2Project/gokart_ws/src/gokart-sensor/configs/purdue/wp.csv
    wp_skiprows: 1
visualize_node:
  ros__parameters:
    config_path: /home/zzjun/ros2Project/gokart_ws/src/gokart-sensor/configs/purdue
    corner_wp_name: corner_wp_idx.npy
    overtake_wp_name: overtake_wp_idx.npy
    wp_delim: ','
    wp_path: /home/zzjun/ros2Project/gokart_ws/src/gokart-sensor/configs/purdue/wp.csv
    wp_skiprows: 1
